name: "Build Flipper App"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
        id: build-app
        with:
          app-dir: '.'

      # ⬇️ ADD THIS STEP TO ACTUALLY SAVE THE FILE ⬇️
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OutputFAP
          path: ${{ steps.build-app.outputs.fap-artifacts }}
