name: "Build Flipper App"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
        with:
          app-dir: '.'
